site_name: Marlyn Wescoff
repo_name: "Marlyn Wescoff"
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T01_MARLYN-WESCOFF.git

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: light blue     
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate
      primary: light blue     
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  font:
    text: Roboto
    code: Roboto Mono
  logo: https://raw.githubusercontent.com/FCTE-Qualidade-de-Software-1/2025-2_T01_MARLYN-WESCOFF/refs/heads/main/docs/images/MarlynWescoff.png
  favicon: https://raw.githubusercontent.com/FCTE-Qualidade-de-Software-1/2025-2_T01_MARLYN-WESCOFF/refs/heads/main/docs/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
    logo: material/code-braces

extra_css:
  - styles/extra.css   

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T01_MARLYN-WESCOFF.git
      name: GitHub Repository

copyright: "Copyright © 2025 - Equipe Marlyn Wescoff"

plugins:
  - search:
      lang: pt

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - Início: index.md
  - Fase 01:
      - 1.1 Propósito da avaliação e uso pretendido: Fase01/criterio1.md
      - 1.2 Requisitante e Partes Interessadas: Fase01/criterio2.md
      - 1.3 Tipo de produto e descrição estruturada do software: Fase01/criterio3.md
      - 1.4 Modelo de qualidade (adaptação + representação gráfica): Fase01/criterio4.md
      - 1.5 Seleção e priorização de características: Fase01/criterio5.md
      - 1.6 Escopo, profundidade e objetos de avaliação: Fase01/criterio6.md
      - 1.7 ODS, metas e indicadores relacionados: Fase01/criterio7.md
      - 1.8 Tabela de Contribuição: Fase01/tabela_de_contribuicao.md
  - Fase 02:
      - 2.1 Introdução e Planejamento da Avaliação (GQM): Fase02/criterio1.md
      - 2.2 Execução da Avaliação - Adequação Funcional: Fase02/criterio2.md
      - 2.3 Execução da Avaliação - Segurança: Fase02/criterio3.md
      - 2.4 Níveis de Pontuação e Critérios de Julgamento: Fase02/pontuacao.md
      - 2.5 Tabela de Contribuição: Fase02/tabela_de_contribuicao.md
  - Fase 03:
      - 3 Planejamento da Avaliação: Fase03/fase3.md
      - 3.1 Tabela de Contribuição: Fase03/tabela_de_contribuicao.md
  - Fase 04:
      - 4 Resultados da Avaliação: Fase04/fase4.md
      - 4.1 Avaliação Adequação Funcional: Fase04/AvAdequacao.md
      - 4.2 Tabela de Contribuição: Fase04/tabela_de_contribuicao.md
  
      
